baseurl: "/CSE232"
url: "https://cse232-msu.github.io"
permalink: /:title

collections:
    labs:
        output: true
    setup:
        output: true
    lectures:
        output: true

defaults:
    - scope:
        path: ""
      values:
        layout: "default"
    - scope:
        path: "labs/"
      values:
        layout: "default"
    - scope:
        path: "setup/"
      values:
        layout: "default"
    - scope:
        path: "lectures/"
      values:
        layout: "default"